unstable_features = true
comment_width = 80
max_width = 120
fn_call_width = 120
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

blank_lines_lower_bound = 1
wrap_comments = true
newline_style = "Unix"
binop_separator = "Back"
group_imports = "StdExternalCrate"
condense_wildcard_suffixes = true
fn_params_layout = "Tall"
edition = "2021"
force_multiline_blocks = false
format_strings = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
indent_style = "Visual"
match_block_trailing_comma = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
fn_single_line = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
